version: '3.8'

services:
  app:
    container_name: DATN-cms-ideas
    build:
      context: .
      dockerfile: .docker/Dockerfile-dev
    volumes:
      - ./:/go/src/github.com/anhhuy1010/DATN-cms-ideas
    ports:
      - 7004:7004
      - 9004:9004
    networks:
      - datn_net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-ideas
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: [ "start", "--config", "/etc/ngrok.yml", "--log", "stdout", "--all" ]
    depends_on:
      - app
    networks:
      - datn_net

networks:
  datn_net:
