// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.24.4
// source: idea.proto

package idea

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListIdeasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListIdeasRequest) Reset() {
	*x = ListIdeasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idea_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIdeasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdeasRequest) ProtoMessage() {}

func (x *ListIdeasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idea_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdeasRequest.ProtoReflect.Descriptor instead.
func (*ListIdeasRequest) Descriptor() ([]byte, []int) {
	return file_idea_proto_rawDescGZIP(), []int{0}
}

func (x *ListIdeasRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIdeasRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Idea struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Ideasname     string `protobuf:"bytes,2,opt,name=ideasname,proto3" json:"ideasname,omitempty"`
	Industry      string `protobuf:"bytes,3,opt,name=industry,proto3" json:"industry,omitempty"`
	ContentDetail string `protobuf:"bytes,4,opt,name=content_detail,json=contentDetail,proto3" json:"content_detail,omitempty"`
	Price         int32  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	PostDay       string `protobuf:"bytes,6,opt,name=post_day,json=postDay,proto3" json:"post_day,omitempty"`
}

func (x *Idea) Reset() {
	*x = Idea{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idea_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Idea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idea) ProtoMessage() {}

func (x *Idea) ProtoReflect() protoreflect.Message {
	mi := &file_idea_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idea.ProtoReflect.Descriptor instead.
func (*Idea) Descriptor() ([]byte, []int) {
	return file_idea_proto_rawDescGZIP(), []int{1}
}

func (x *Idea) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Idea) GetIdeasname() string {
	if x != nil {
		return x.Ideasname
	}
	return ""
}

func (x *Idea) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *Idea) GetContentDetail() string {
	if x != nil {
		return x.ContentDetail
	}
	return ""
}

func (x *Idea) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Idea) GetPostDay() string {
	if x != nil {
		return x.PostDay
	}
	return ""
}

type ListIdeasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ideas []*Idea `protobuf:"bytes,1,rep,name=ideas,proto3" json:"ideas,omitempty"`
}

func (x *ListIdeasResponse) Reset() {
	*x = ListIdeasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idea_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIdeasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdeasResponse) ProtoMessage() {}

func (x *ListIdeasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idea_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdeasResponse.ProtoReflect.Descriptor instead.
func (*ListIdeasResponse) Descriptor() ([]byte, []int) {
	return file_idea_proto_rawDescGZIP(), []int{2}
}

func (x *ListIdeasResponse) GetIdeas() []*Idea {
	if x != nil {
		return x.Ideas
	}
	return nil
}

var File_idea_proto protoreflect.FileDescriptor

var file_idea_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x69, 0x64, 0x65, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x64,
	0x65, 0x61, 0x22, 0x3c, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x65, 0x61, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0xac, 0x01, 0x0a, 0x04, 0x49, 0x64, 0x65, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x64, 0x65, 0x61, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x69, 0x64, 0x65, 0x61, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x79, 0x22,
	0x35, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x65, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x69, 0x64, 0x65, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x69, 0x64, 0x65, 0x61, 0x2e, 0x49, 0x64, 0x65, 0x61, 0x52,
	0x05, 0x69, 0x64, 0x65, 0x61, 0x73, 0x32, 0x4b, 0x0a, 0x0b, 0x49, 0x64, 0x65, 0x61, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x65,
	0x61, 0x73, 0x12, 0x16, 0x2e, 0x69, 0x64, 0x65, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64,
	0x65, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x69, 0x64, 0x65,
	0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x65, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6e, 0x68, 0x68, 0x75, 0x79, 0x31, 0x30, 0x31, 0x30, 0x2f, 0x44, 0x41, 0x54,
	0x4e, 0x2d, 0x63, 0x6d, 0x73, 0x2d, 0x69, 0x64, 0x65, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x64, 0x65, 0x61, 0x3b, 0x69, 0x64, 0x65, 0x61,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idea_proto_rawDescOnce sync.Once
	file_idea_proto_rawDescData = file_idea_proto_rawDesc
)

func file_idea_proto_rawDescGZIP() []byte {
	file_idea_proto_rawDescOnce.Do(func() {
		file_idea_proto_rawDescData = protoimpl.X.CompressGZIP(file_idea_proto_rawDescData)
	})
	return file_idea_proto_rawDescData
}

var file_idea_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_idea_proto_goTypes = []interface{}{
	(*ListIdeasRequest)(nil),  // 0: idea.ListIdeasRequest
	(*Idea)(nil),              // 1: idea.Idea
	(*ListIdeasResponse)(nil), // 2: idea.ListIdeasResponse
}
var file_idea_proto_depIdxs = []int32{
	1, // 0: idea.ListIdeasResponse.ideas:type_name -> idea.Idea
	0, // 1: idea.IdeaService.ListIdeas:input_type -> idea.ListIdeasRequest
	2, // 2: idea.IdeaService.ListIdeas:output_type -> idea.ListIdeasResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idea_proto_init() }
func file_idea_proto_init() {
	if File_idea_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idea_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIdeasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idea_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Idea); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idea_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIdeasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idea_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idea_proto_goTypes,
		DependencyIndexes: file_idea_proto_depIdxs,
		MessageInfos:      file_idea_proto_msgTypes,
	}.Build()
	File_idea_proto = out.File
	file_idea_proto_rawDesc = nil
	file_idea_proto_goTypes = nil
	file_idea_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IdeaServiceClient is the client API for IdeaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdeaServiceClient interface {
	ListIdeas(ctx context.Context, in *ListIdeasRequest, opts ...grpc.CallOption) (*ListIdeasResponse, error)
}

type ideaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdeaServiceClient(cc grpc.ClientConnInterface) IdeaServiceClient {
	return &ideaServiceClient{cc}
}

func (c *ideaServiceClient) ListIdeas(ctx context.Context, in *ListIdeasRequest, opts ...grpc.CallOption) (*ListIdeasResponse, error) {
	out := new(ListIdeasResponse)
	err := c.cc.Invoke(ctx, "/idea.IdeaService/ListIdeas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdeaServiceServer is the server API for IdeaService service.
type IdeaServiceServer interface {
	ListIdeas(context.Context, *ListIdeasRequest) (*ListIdeasResponse, error)
}

// UnimplementedIdeaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIdeaServiceServer struct {
}

func (*UnimplementedIdeaServiceServer) ListIdeas(context.Context, *ListIdeasRequest) (*ListIdeasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIdeas not implemented")
}

func RegisterIdeaServiceServer(s *grpc.Server, srv IdeaServiceServer) {
	s.RegisterService(&_IdeaService_serviceDesc, srv)
}

func _IdeaService_ListIdeas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdeasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeaServiceServer).ListIdeas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idea.IdeaService/ListIdeas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeaServiceServer).ListIdeas(ctx, req.(*ListIdeasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdeaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idea.IdeaService",
	HandlerType: (*IdeaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIdeas",
			Handler:    _IdeaService_ListIdeas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idea.proto",
}
