// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.24.4
// source: idea.proto

package idea

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIdeaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerUuid  string `protobuf:"bytes,1,opt,name=customer_uuid,json=customerUuid,proto3" json:"customer_uuid,omitempty"`
	CustomerName  string `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerEmail string `protobuf:"bytes,3,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	IdeasName     string `protobuf:"bytes,4,opt,name=ideas_name,json=ideasName,proto3" json:"ideas_name,omitempty"`
	Industry      string `protobuf:"bytes,5,opt,name=industry,proto3" json:"industry,omitempty"`
	ContentDetail string `protobuf:"bytes,6,opt,name=content_detail,json=contentDetail,proto3" json:"content_detail,omitempty"`
	Price         int32  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *CreateIdeaRequest) Reset() {
	*x = CreateIdeaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idea_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIdeaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIdeaRequest) ProtoMessage() {}

func (x *CreateIdeaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idea_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIdeaRequest.ProtoReflect.Descriptor instead.
func (*CreateIdeaRequest) Descriptor() ([]byte, []int) {
	return file_idea_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIdeaRequest) GetCustomerUuid() string {
	if x != nil {
		return x.CustomerUuid
	}
	return ""
}

func (x *CreateIdeaRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CreateIdeaRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *CreateIdeaRequest) GetIdeasName() string {
	if x != nil {
		return x.IdeasName
	}
	return ""
}

func (x *CreateIdeaRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CreateIdeaRequest) GetContentDetail() string {
	if x != nil {
		return x.ContentDetail
	}
	return ""
}

func (x *CreateIdeaRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateIdeaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateIdeaResponse) Reset() {
	*x = CreateIdeaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idea_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIdeaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIdeaResponse) ProtoMessage() {}

func (x *CreateIdeaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idea_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIdeaResponse.ProtoReflect.Descriptor instead.
func (*CreateIdeaResponse) Descriptor() ([]byte, []int) {
	return file_idea_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIdeaResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CreateIdeaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_idea_proto protoreflect.FileDescriptor

var file_idea_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x69, 0x64, 0x65, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x64,
	0x65, 0x61, 0x22, 0xfc, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x64, 0x65,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x65,
	0x61, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x64, 0x65, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x64, 0x75,
	0x73, 0x74, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x64, 0x75,
	0x73, 0x74, 0x72, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x22, 0x42, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x64, 0x65, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4e, 0x0a, 0x0b, 0x49, 0x64, 0x65, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x65, 0x61, 0x12, 0x17, 0x2e, 0x69, 0x64, 0x65, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x69, 0x64,
	0x65, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x68, 0x68, 0x75, 0x79, 0x31, 0x30, 0x31, 0x30, 0x2f, 0x44,
	0x41, 0x54, 0x4e, 0x2d, 0x63, 0x6d, 0x73, 0x2d, 0x69, 0x64, 0x65, 0x61, 0x73, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x64, 0x65, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idea_proto_rawDescOnce sync.Once
	file_idea_proto_rawDescData = file_idea_proto_rawDesc
)

func file_idea_proto_rawDescGZIP() []byte {
	file_idea_proto_rawDescOnce.Do(func() {
		file_idea_proto_rawDescData = protoimpl.X.CompressGZIP(file_idea_proto_rawDescData)
	})
	return file_idea_proto_rawDescData
}

var file_idea_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idea_proto_goTypes = []interface{}{
	(*CreateIdeaRequest)(nil),  // 0: idea.CreateIdeaRequest
	(*CreateIdeaResponse)(nil), // 1: idea.CreateIdeaResponse
}
var file_idea_proto_depIdxs = []int32{
	0, // 0: idea.IdeaService.CreateIdea:input_type -> idea.CreateIdeaRequest
	1, // 1: idea.IdeaService.CreateIdea:output_type -> idea.CreateIdeaResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idea_proto_init() }
func file_idea_proto_init() {
	if File_idea_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idea_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIdeaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idea_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIdeaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idea_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idea_proto_goTypes,
		DependencyIndexes: file_idea_proto_depIdxs,
		MessageInfos:      file_idea_proto_msgTypes,
	}.Build()
	File_idea_proto = out.File
	file_idea_proto_rawDesc = nil
	file_idea_proto_goTypes = nil
	file_idea_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IdeaServiceClient is the client API for IdeaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdeaServiceClient interface {
	CreateIdea(ctx context.Context, in *CreateIdeaRequest, opts ...grpc.CallOption) (*CreateIdeaResponse, error)
}

type ideaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdeaServiceClient(cc grpc.ClientConnInterface) IdeaServiceClient {
	return &ideaServiceClient{cc}
}

func (c *ideaServiceClient) CreateIdea(ctx context.Context, in *CreateIdeaRequest, opts ...grpc.CallOption) (*CreateIdeaResponse, error) {
	out := new(CreateIdeaResponse)
	err := c.cc.Invoke(ctx, "/idea.IdeaService/CreateIdea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdeaServiceServer is the server API for IdeaService service.
type IdeaServiceServer interface {
	CreateIdea(context.Context, *CreateIdeaRequest) (*CreateIdeaResponse, error)
}

// UnimplementedIdeaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIdeaServiceServer struct {
}

func (*UnimplementedIdeaServiceServer) CreateIdea(context.Context, *CreateIdeaRequest) (*CreateIdeaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIdea not implemented")
}

func RegisterIdeaServiceServer(s *grpc.Server, srv IdeaServiceServer) {
	s.RegisterService(&_IdeaService_serviceDesc, srv)
}

func _IdeaService_CreateIdea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIdeaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeaServiceServer).CreateIdea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idea.IdeaService/CreateIdea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeaServiceServer).CreateIdea(ctx, req.(*CreateIdeaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdeaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idea.IdeaService",
	HandlerType: (*IdeaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIdea",
			Handler:    _IdeaService_CreateIdea_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idea.proto",
}
